cp “Template PMW Pro.docx”  "T0180 Template Beslisdocument.docx"
cp “Template PMW Pro.docx”  "T0181 Template Communicatieplan.docx"
cp “Template PMW Pro.docx”  "T0182 Template Evaluatierapport.docx"
cp “Template PMW Pro.docx”  "T0183 Template Faseplan.docx"
cp “Template PMW Pro.docx”  "T0184 Template Projecteindrapport.docx"
cp “Template PMW Pro.docx”  "T0185 Template Projectoverdracht.docx"
cp “Template PMW Pro.docx”  "T0186 Template Projectplan.docx"
cp “Template PMW Pro.docx”  "T0187 Template Projectvoorstel.docx"
cp “Template PMW Pro.docx”  "T0189 Template Stakeholdersanalyse.docx"
cp “Template PMW Pro.docx”  "T0190 Template Teamplan.docx"
cp “Template PMW Pro.docx”  "T0191 Template Werkpakket.docx"
cp “Template PMW Pro.docx”  "T0192 Template Wijzigingsverzoek.docx"
cp “Template PMW Pro.docx”  "T0207 Template Nieuwe aanvraag.docx"
cp “Template PMW Pro.docx”  "W0139 Handleiding PMW Projectmanagement.docx"
